### ISSUE TITLE
`./lychee.toml` does not exist, is it `./lychee.example.toml`?

### ISSUE THREAD

**Issue by YDX-2147483647** [lycheeverse/lycheeverse.github.io#5]
The [website](https://lychee.cli.rs/#/usage/config?id=default-configuration-file) says `./lychee.toml` is the default config, but it does not exist. Is it `./lychee.example.toml` (introduced in https://github.com/lycheeverse/lychee/pull/16)?

https://github.com/lycheeverse/lycheeverse.github.io/blob/99ef14894852cf94b30ee6db763a4838d578cee3/usage/config.md?plain=1#L20-L24

---

Besides, _default_ really confuses me here. I guess CLI options fallback to `./lychee.toml` or `--config` (configuration file), and they fallback to something internal (default configuration).

> The **configuration file** is also used to specify the default values for the options that are also available on the command line.

> The **default** configuration file is `./lychee.toml` and is used if no other configuration file is specified. Here is an **example** of the **default** configuration file.

Maybe the following is better?

> `./lychee.toml` is used as the configuration file if no other configuration file is specified. Here is an example of the configuration file.
>
> Please find the latest example…

(I can make a PR if you want, but I'm not sure I understand it right.)

**Comment by mre** [comment]
Yes, lychee.toml is the correct name.  The idea is that a user can make a copy of lychee.example.toml and make changes.

What I meant by default config was that it will be used automatically if it exists. You don't have to pass any CLI option for that. Maybe "default config name" would have been a better way to phrase it? I do think that other cli tools describe it the same way, though, but I might be wrong.

We can work on the wording. Feel free to create a pull request with your proposal.

**Comment by YDX-2147483647** [comment]
How about “default config _location_”?

---

The followings are some manuals for other tools, time-honored or brand new.

- [ssh](https://man.openbsd.org/ssh#F)

  >  `-F configfile` specifies an alternative per-user configuration file. If a configuration file is given on the command line, the system-wide configuration file (…) will be ignored. The default for the per-user configuration file is `~/.ssh/config`. If set to “none”, no configuration files will be read.

- [bat](https://github.com/sharkdp/bat#configuration-file)

  > You can use the `BAT_CONFIG_PATH` environment variable to point `bat` to a non-default location of the configuration file.

  > A default configuration file can be created with the `--generate-config-file` option.

- [matplotlib](https://matplotlib.org/stable/tutorials/introductory/customizing.html)

  > Matplotlib looks for matplotlibrc in four locations, in the following order:
  >
  > 1. `matplotlibrc` in the current working directory, …

  > The default matplotlibrc file:
  >
  > ```yaml
  > #### MATPLOTLIBRC FORMAT
  > 
  > ## NOTE FOR END USERS: DO NOT EDIT THIS FILE!
  > ##
  > ## This is a sample Matplotlib configuration file - you can find a copy
  > ## of it on your system in …
  > ## DO NOT EDIT IT!
  > ##
  > ## If you wish to change your default style, copy this file to one of the
  > ## following locations: …
  > ## and edit that copy.
  > 
  > ##### CONFIGURATION BEGINS HERE
  > #timezone:    UTC       # a pytz timezone string, e.g., US/Central or Europe/Paris
  > …
  > ```

**Comment by mre** [comment]
Yes, that makes a lot of sense! Thanks for doing the research. 🌟
