### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AndrewKvalheim** [lycheeverse/lycheeverse.github.io#69]
At [`/recipes/relative-links/`](https://lychee.cli.rs/recipes/relative-links/) there is a broken link to [`../usage/cli`](https://lychee.cli.rs/recipes/usage/cli). While correcting that one link is trivial, given the nature of this project it’s a concerning discovery that warrants broader review.

**Comment by jacobdalamb** [comment]
> At [`/recipes/relative-links/`](https://lychee.cli.rs/recipes/relative-links/) there is a broken link to [`../usage/cli`](https://lychee.cli.rs/recipes/usage/cli). While correcting that one link is trivial, given the nature of this project it’s a concerning discovery that warrants broader review.

@AndrewKvalheim I'm not familiar with the github workflow that checks links on the site but running a check locally showed that the broken link you reported seems to be the only one.

**Comment by mre** [comment]
Thanks to both of you.
I've updated the link checker now. It detected the broken link in my tests. As @jacobdalamb, it was the only one.
There were a few more false-positives, that I excluded. We should be good now.
