### ISSUE TITLE
accept as strings array errors

### ISSUE THREAD

**Issue by o-az** [lycheeverse/lycheeverse.github.io#72]
https://github.com/lycheeverse/lycheeverse.github.io/blob/8f8ea2cc4a2ddd311ba167e9a7e48037fd00dbbd/src/content/docs/usage/config.md?plain=1#L79-L83

works:
```toml
accept = [200, 429, 307]
```
error:
```toml
accept = ["200", "429", "307"]
```

![CleanShot 2024-02-22 at 19 53 34](https://github.com/lycheeverse/lycheeverse.github.io/assets/23618431/e7b55808-0144-458c-83db-685a565bebaf)

**Comment by mre** [comment]
Works for me. Are you on the latest version?

```
❯ lychee -V
lychee 0.14.3
❯ cat lychee.toml
accept = ["200", "429", "307"]
❯ echo "https://wikipedia.org" | lychee --config lychee.toml -
🔍 1 Total (in 0s) ✅ 1 OK 🚫 0 Errors
```
