### ISSUE TITLE
Add example for using the Docker image with the `--cache` option

### ISSUE THREAD

**Issue by ehmicky** [lycheeverse/lycheeverse.github.io#79]
What are your thoughts on adding an example on how to use both Docker and the `--cache` option together?

I do not think the current example for Docker works when setting that option, as the `.lycheecache` file is written in the container but not in the host machine.

**Comment by mre** [comment]
Sure. Do you want to take a stab at it? There's probably an example on GitHub where someone did that, which we could take.

**Comment by ehmicky** [comment]
Thanks for your response @mre!

I actually filed this issue because I was having issues figuring it out myself, so I was hoping there was some code sample somewhere already. :) 

I checked if anyone mentioned in this repository or the other repositories of this organization, but this does not seemed to be the case.

**Comment by mre** [comment]
Ah, I see. You mean like that? https://lychee.cli.rs/github_action_recipes/caching/#caching-in-github-actions

**Comment by ehmicky** [comment]
Yes, but without GitHub actions. I am running lychee locally.

**Comment by mre** [comment]
I wrote a few words here: http://localhost:4321/recipes/caching.
Let me know if that works for you.

**Comment by ehmicky** [comment]
Yes, this works, thanks a lot!
