### ISSUE TITLE
Local astro dev

### ISSUE THREAD

**Issue by Isengo1989** [lycheeverse/lycheeverse.github.io#84]
Not sure if `astro dev` should run simply like that or other configs are needed.

![image](https://github.com/user-attachments/assets/311ab0dc-2ae2-46fa-8b48-689e2dee9193)

**Comment by mre** [comment]
Huh, it works on my end. Didn't make any modifications. Very strange.

**Comment by Isengo1989** [comment]
> Huh, it works on my end. Didn't make any modifications. Very strange.

:man_shrugging: Simply did a

`npm install -g astro`

 `npm i`

`astro dev`

Here are my node versions. Nothing else to setup? A env file or smth?

![image](https://github.com/user-attachments/assets/a4a34d17-79bb-494d-9e52-c43b1dd65890)

**Comment by Isengo1989** [comment]
Hmm,

`npm run dev` works and `astro dev` not :thinking: 

EDIT: Meeh, to use astro directly as mentioned in the Readme I installed it via

`npm -g install astro` ,which installed v5 instead of the in the project used v4

Maybe you could add

`npm run dev` instead or add the v4 install command `npm -g install astro@4`

**Comment by mre** [comment]
Good point. I've extended the development instructions.
https://github.com/lycheeverse/lycheeverse.github.io/commit/b7932a5d414da04f68cbae118dec96505e3fac6a
@jacobdalamb fyi
